Repository pagopa/pagopa-api-config-testing-support, pull requests merged in 2025-06, with the labels that each got.

#8 chore: Disabled Nexi in dev
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: patch, size/small

#9 chore: adding wl identity Pidm-487
  .github/workflows/03_code_review.yml
  .github/workflows/04h_deploy_with_github_runner.yml
  .identity/00_data.tf
  .identity/03_github_environment.tf
  .identity/99_main.tf
  Dockerfile
  README.md
  helm/Chart.lock
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
Labels: enhancement, patch

#11 fix slack channel
  .identity/.terraform.lock.hcl
  .identity/00_data.tf
Labels: ignore-for-release, size/small
